LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_PROJECT = "pr-long-replacement-23"
MISTRAL_API_KEY = "OWEMpjjsDfW4CEJ5gl1ZC52gjBOqFOu5"
PINECONE_API_KEY = "pcsk_4CJx2t_Mrw4gnAyaL5xabNm1TVzDRAo3LQAKp5McKDd2evMhjgt1BzZ6VesJwmVU5envBE"